### authenticate user
GET http://localhost:3000/best-agents
Content-Type: application/json



### register user

POST http://localhost:3000/register
Content-Type: application/json

{
    "id": "ta1008",
    "firstname": "John",
    "lastname": "Doe",
    "email": "johndoe@gmail.com",
    "password": "Admin",
    "role": "User"
}